### PR TITLE
Fixed expectation bug for local level and structural model

### LINKED ISSUE #176: Shift between forecast and simulation scenarions in 0.4 branch
From the `"Basic Structural Model"` test in the `refactor-to-0.4` branch:

```
julia> forec.expected_value
10-element Array{Array{Float64,1},1}:
 [6.083167302258863]
 [6.1946408652357725]
 [6.2159346905082975]
 [6.224800298528862]
 [6.342665144161216]
 [6.478336552034039]
 [6.4752275105634185]
 [6.305246285595047]
 [6.2049769753007]
 [6.068300933194807]

julia> expected_value_of_scenarios(scenarios)
10-element Array{Array{Float64,1},1}:
 [6.125259198552738]
 [6.082992264095608]
 [6.19469004566561]
 [6.215805308795272]
 [6.224534124065003]
 [6.342838593417967]
 [6.478180596529146]
 [6.475235575886917]
 [6.305295124889548]
 [6.205057985402772]
```

There is a clear shift of one time period between both.

Note that this should be caught in the tests, but they're currently using `atol = 1.0` which is super large. We should use `rtol = 1e-3` or even lower for this.

### PR DESCRIPTION
**Pull request by guilhermebodin**
Fixed the bug of #176 but I still need to check if the ARIMA model is correct

Closes #176

### CODE REVIEW

File: test/utils.jl [hunk 1]
```diff
@@ -2,39 +2,36 @@ read_csv(file::String) = DataFrame!(CSV.File(file))
...
     end
     return expected_values
 end
 
 function test_scenarios_adequacy_with_forecast(forec::StateSpaceModels.Forecast, 
-                                               scenarios::Array{T, 3}, 
-                                               expected_value_atol::T,
-                                               quantiles_atol::T) where T
+                                               scenarios::Array{T,3}; 
+                                               expected_value_rtol::T=1e-2,
```
Comment (raphaelsaavedra) [inline test/utils.jl:22]: I would use a lower value here, 1e-3 or 1e-4. I expect it to pass the tests even with 1e-4 given the examples I've seen.

File: test/models/arima.jl [hunk 2]
```diff
@@ -11,8 +11,8 @@
     forec = forecast(model, 10)
     @test monotone_forecast_variance(forec)
     # simualting
-    scenarios = simulate_scenarios(model, 10, 10_000)
-    test_scenarios_adequacy_with_forecast(forec, scenarios, 1.0, 6.0)
+    # scenarios = simulate_scenarios(model, 10, 10_000)
```
Comment (raphaelsaavedra) [inline test/models/arima.jl:14]: Just need to ensure this works too and then it will look good to me

File: test/utils.jl (hunk 1 above)
Comment (guilhermebodin) [reply test/utils.jl:22]: It did not work for `1e-3` we could try making it with `Distributions.jl` to see if there is any difference.

Comment (raphaelsaavedra) [reply test/utils.jl:22]: I think the quantile test is too strong and will inevitably fail. See:

```
julia> dist = Normal(250.0, 1500.0)
Normal{Float64}(μ=250.0, σ=1500.0)

julia> dist = Normal(250.0, 1500.0);

julia> v = rand(dist, 100_000);

julia> quantile(dist, 0.05)
-2217.2804404272088

julia> quantile(v, 0.05)
-2212.105104144297

julia> 100*(1 - quantile(v, 0.05) / quantile(dist, 0.05))
0.2334091885063727
```

0.23% error even when computing 100,000 scenarios.
I think having good accuracy on sampled quantiles is complicated because `quantile` uses linear interpolation which might be sketchy.

I would remove the quantile test and keep only the test on the expected value, with `rtol=1e-3`. I have just tested it and it passes.

**Comment by raphaelsaavedra** [comment]
Closes #176

**Comment by guilhermebodin** [comment]
@raphaelsaavedra Some of the jobs passed and others did not, this is mainly because the `rtol` is too small, I think we should consider loosen up a little, to `1e-2` or to `5e-3` as default.

File: test/models/basicstructural.jl [hunk 3]
```diff
@@ -12,6 +12,6 @@
     forec = forecast(model, 10)
     @test monotone_forecast_variance(forec)
     # simualting
-    scenarios = simulate_scenarios(model, 10, 10_000)
-    test_scenarios_adequacy_with_forecast(forec, scenarios, 0.2, 0.2)
+    scenarios = simulate_scenarios(model, 10, 100_000)
```
Comment (raphaelsaavedra) [inline test/models/basicstructural.jl:15]: I think this test passes with `10_000`

File: test/utils.jl [hunk 4]
```diff
@@ -1,39 +1,32 @@
...
     end
     return expected_values
 end
 
 function test_scenarios_adequacy_with_forecast(forec::StateSpaceModels.Forecast, 
-                                               scenarios::Array{T, 3}, 
-                                               expected_value_atol::T,
-                                               quantiles_atol::T) where T
+                                               scenarios::Array{T,3}; 
+                                               expected_value_rtol::T=5e-3,
```
Comment (raphaelsaavedra) [inline test/utils.jl:20]: just call these arguments `rtol` and `atol` for simplicity

**Review by raphaelsaavedra — APPROVED** [review]
Feel free to merge!
